#!/bin/sh
. test/lib.sh

begin "Indents indented text"
scdoc <<EOF | grep ".RS 4" >/dev/null
test(8)

Not indented
	Indented one level
EOF
end 0

begin "Deindents following indented text"
scdoc <<EOF | grep ".RE" >/dev/null
test(8)

Not indented
	Indented one level
Not indented
EOF
end 0

begin "Disallows indentation changes > 1"
scdoc <<EOF >/dev/null
test(8)

Not indented
	Indented one level
			Indented three levels
Not indented
EOF
end 1
